CREATE TABLE IF NOT EXISTS Program (
  program_id VARCHAR(20) PRIMARY KEY,
  program_name VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
