CREATE TABLE IF NOT EXISTS otpHOP (
  otp_hop_id      INT AUTO_INCREMENT PRIMARY KEY,
  hop_id          INT NULL,
  otp_code        VARCHAR(255) NOT NULL,
  otp_status      BOOLEAN DEFAULT TRUE,
  expires_at      DATETIME NOT NULL,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_hop_otp
    FOREIGN KEY (hop_id)
    REFERENCES HOP (hop_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

